/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SellerVerificationRouteImport } from './routes/seller.verification'
import { Route as SellerTransactionsRouteImport } from './routes/seller.transactions'
import { Route as SellerSettingsRouteImport } from './routes/seller.settings'
import { Route as SellerSafepayRouteImport } from './routes/seller.safepay'
import { Route as SellerProtectedDealRouteImport } from './routes/seller.protected-deal'
import { Route as SellerNotificationsRouteImport } from './routes/seller.notifications'
import { Route as SellerDeliveriesRouteImport } from './routes/seller.deliveries'
import { Route as SellerCustomersRouteImport } from './routes/seller.customers'
import { Route as SellerAccountRouteImport } from './routes/seller.account'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthRoleRouteImport } from './routes/auth.role'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthKycRouteImport } from './routes/auth.kyc'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AppVerificationRouteImport } from './routes/app.verification'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppTrackRouteImport } from './routes/app.track'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSellersRouteImport } from './routes/app.sellers'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppSafepayRouteImport } from './routes/app.safepay'
import { Route as AppPayRouteImport } from './routes/app.pay'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppNewEscrowRouteImport } from './routes/app.new-escrow'
import { Route as AppDisputesRouteImport } from './routes/app.disputes'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AppTransactionIdRouteImport } from './routes/app.transaction.$id'
import { Route as AppTrackingIdRouteImport } from './routes/app.tracking.$id'
import { Route as AppSellerIdRouteImport } from './routes/app.seller.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SellerVerificationRoute = SellerVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => SellerRoute,
} as any)
const SellerTransactionsRoute = SellerTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSafepayRoute = SellerSafepayRouteImport.update({
  id: '/safepay',
  path: '/safepay',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProtectedDealRoute = SellerProtectedDealRouteImport.update({
  id: '/protected-deal',
  path: '/protected-deal',
  getParentRoute: () => SellerRoute,
} as any)
const SellerNotificationsRoute = SellerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SellerRoute,
} as any)
const SellerDeliveriesRoute = SellerDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => SellerRoute,
} as any)
const SellerCustomersRoute = SellerCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAccountRoute = SellerAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SellerRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/role',
  path: '/auth/role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthKycRoute = AuthKycRouteImport.update({
  id: '/auth/kyc',
  path: '/auth/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackRoute = AppTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSellersRoute = AppSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppSafepayRoute = AppSafepayRouteImport.update({
  id: '/safepay',
  path: '/safepay',
  getParentRoute: () => AppRoute,
} as any)
const AppPayRoute = AppPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNewEscrowRoute = AppNewEscrowRouteImport.update({
  id: '/new-escrow',
  path: '/new-escrow',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputesRoute = AppDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/admin/sellers',
  path: '/admin/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionIdRoute = AppTransactionIdRouteImport.update({
  id: '/transaction/$id',
  path: '/transaction/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingIdRoute = AppTrackingIdRouteImport.update({
  id: '/tracking/$id',
  path: '/tracking/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSellerIdRoute = AppSellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/seller': typeof SellerRouteWithChildren
  '/share': typeof ShareRoute
  '/terms': typeof TermsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/app/account': typeof AppAccountRoute
  '/app/disputes': typeof AppDisputesRoute
  '/app/new-escrow': typeof AppNewEscrowRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pay': typeof AppPayRoute
  '/app/safepay': typeof AppSafepayRoute
  '/app/scan': typeof AppScanRoute
  '/app/sellers': typeof AppSellersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/track': typeof AppTrackRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/verification': typeof AppVerificationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/kyc': typeof AuthKycRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/seller/account': typeof SellerAccountRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/deliveries': typeof SellerDeliveriesRoute
  '/seller/notifications': typeof SellerNotificationsRoute
  '/seller/protected-deal': typeof SellerProtectedDealRoute
  '/seller/safepay': typeof SellerSafepayRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/transactions': typeof SellerTransactionsRoute
  '/seller/verification': typeof SellerVerificationRoute
  '/app/': typeof AppIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/app/seller/$id': typeof AppSellerIdRoute
  '/app/tracking/$id': typeof AppTrackingIdRoute
  '/app/transaction/$id': typeof AppTransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/share': typeof ShareRoute
  '/terms': typeof TermsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/app/account': typeof AppAccountRoute
  '/app/disputes': typeof AppDisputesRoute
  '/app/new-escrow': typeof AppNewEscrowRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pay': typeof AppPayRoute
  '/app/safepay': typeof AppSafepayRoute
  '/app/scan': typeof AppScanRoute
  '/app/sellers': typeof AppSellersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/track': typeof AppTrackRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/verification': typeof AppVerificationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/kyc': typeof AuthKycRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/seller/account': typeof SellerAccountRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/deliveries': typeof SellerDeliveriesRoute
  '/seller/notifications': typeof SellerNotificationsRoute
  '/seller/protected-deal': typeof SellerProtectedDealRoute
  '/seller/safepay': typeof SellerSafepayRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/transactions': typeof SellerTransactionsRoute
  '/seller/verification': typeof SellerVerificationRoute
  '/app': typeof AppIndexRoute
  '/seller': typeof SellerIndexRoute
  '/app/seller/$id': typeof AppSellerIdRoute
  '/app/tracking/$id': typeof AppTrackingIdRoute
  '/app/transaction/$id': typeof AppTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/seller': typeof SellerRouteWithChildren
  '/share': typeof ShareRoute
  '/terms': typeof TermsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/app/account': typeof AppAccountRoute
  '/app/disputes': typeof AppDisputesRoute
  '/app/new-escrow': typeof AppNewEscrowRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pay': typeof AppPayRoute
  '/app/safepay': typeof AppSafepayRoute
  '/app/scan': typeof AppScanRoute
  '/app/sellers': typeof AppSellersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/track': typeof AppTrackRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/verification': typeof AppVerificationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/kyc': typeof AuthKycRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/seller/account': typeof SellerAccountRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/deliveries': typeof SellerDeliveriesRoute
  '/seller/notifications': typeof SellerNotificationsRoute
  '/seller/protected-deal': typeof SellerProtectedDealRoute
  '/seller/safepay': typeof SellerSafepayRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/transactions': typeof SellerTransactionsRoute
  '/seller/verification': typeof SellerVerificationRoute
  '/app/': typeof AppIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/app/seller/$id': typeof AppSellerIdRoute
  '/app/tracking/$id': typeof AppTrackingIdRoute
  '/app/transaction/$id': typeof AppTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/help'
    | '/privacy'
    | '/seller'
    | '/share'
    | '/terms'
    | '/admin/sellers'
    | '/app/account'
    | '/app/disputes'
    | '/app/new-escrow'
    | '/app/notifications'
    | '/app/pay'
    | '/app/safepay'
    | '/app/scan'
    | '/app/sellers'
    | '/app/settings'
    | '/app/track'
    | '/app/transactions'
    | '/app/verification'
    | '/auth/forgot'
    | '/auth/kyc'
    | '/auth/login'
    | '/auth/role'
    | '/auth/signup'
    | '/auth/verify'
    | '/seller/account'
    | '/seller/customers'
    | '/seller/deliveries'
    | '/seller/notifications'
    | '/seller/protected-deal'
    | '/seller/safepay'
    | '/seller/settings'
    | '/seller/transactions'
    | '/seller/verification'
    | '/app/'
    | '/seller/'
    | '/app/seller/$id'
    | '/app/tracking/$id'
    | '/app/transaction/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/help'
    | '/privacy'
    | '/share'
    | '/terms'
    | '/admin/sellers'
    | '/app/account'
    | '/app/disputes'
    | '/app/new-escrow'
    | '/app/notifications'
    | '/app/pay'
    | '/app/safepay'
    | '/app/scan'
    | '/app/sellers'
    | '/app/settings'
    | '/app/track'
    | '/app/transactions'
    | '/app/verification'
    | '/auth/forgot'
    | '/auth/kyc'
    | '/auth/login'
    | '/auth/role'
    | '/auth/signup'
    | '/auth/verify'
    | '/seller/account'
    | '/seller/customers'
    | '/seller/deliveries'
    | '/seller/notifications'
    | '/seller/protected-deal'
    | '/seller/safepay'
    | '/seller/settings'
    | '/seller/transactions'
    | '/seller/verification'
    | '/app'
    | '/seller'
    | '/app/seller/$id'
    | '/app/tracking/$id'
    | '/app/transaction/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/help'
    | '/privacy'
    | '/seller'
    | '/share'
    | '/terms'
    | '/admin/sellers'
    | '/app/account'
    | '/app/disputes'
    | '/app/new-escrow'
    | '/app/notifications'
    | '/app/pay'
    | '/app/safepay'
    | '/app/scan'
    | '/app/sellers'
    | '/app/settings'
    | '/app/track'
    | '/app/transactions'
    | '/app/verification'
    | '/auth/forgot'
    | '/auth/kyc'
    | '/auth/login'
    | '/auth/role'
    | '/auth/signup'
    | '/auth/verify'
    | '/seller/account'
    | '/seller/customers'
    | '/seller/deliveries'
    | '/seller/notifications'
    | '/seller/protected-deal'
    | '/seller/safepay'
    | '/seller/settings'
    | '/seller/transactions'
    | '/seller/verification'
    | '/app/'
    | '/seller/'
    | '/app/seller/$id'
    | '/app/tracking/$id'
    | '/app/transaction/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  SellerRoute: typeof SellerRouteWithChildren
  ShareRoute: typeof ShareRoute
  TermsRoute: typeof TermsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthKycRoute: typeof AuthKycRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRoleRoute: typeof AuthRoleRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/seller/verification': {
      id: '/seller/verification'
      path: '/verification'
      fullPath: '/seller/verification'
      preLoaderRoute: typeof SellerVerificationRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/transactions': {
      id: '/seller/transactions'
      path: '/transactions'
      fullPath: '/seller/transactions'
      preLoaderRoute: typeof SellerTransactionsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/safepay': {
      id: '/seller/safepay'
      path: '/safepay'
      fullPath: '/seller/safepay'
      preLoaderRoute: typeof SellerSafepayRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/protected-deal': {
      id: '/seller/protected-deal'
      path: '/protected-deal'
      fullPath: '/seller/protected-deal'
      preLoaderRoute: typeof SellerProtectedDealRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/notifications': {
      id: '/seller/notifications'
      path: '/notifications'
      fullPath: '/seller/notifications'
      preLoaderRoute: typeof SellerNotificationsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/deliveries': {
      id: '/seller/deliveries'
      path: '/deliveries'
      fullPath: '/seller/deliveries'
      preLoaderRoute: typeof SellerDeliveriesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/customers': {
      id: '/seller/customers'
      path: '/customers'
      fullPath: '/seller/customers'
      preLoaderRoute: typeof SellerCustomersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/account': {
      id: '/seller/account'
      path: '/account'
      fullPath: '/seller/account'
      preLoaderRoute: typeof SellerAccountRouteImport
      parentRoute: typeof SellerRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/role': {
      id: '/auth/role'
      path: '/auth/role'
      fullPath: '/auth/role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/kyc': {
      id: '/auth/kyc'
      path: '/auth/kyc'
      fullPath: '/auth/kyc'
      preLoaderRoute: typeof AuthKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/verification': {
      id: '/app/verification'
      path: '/verification'
      fullPath: '/app/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/track': {
      id: '/app/track'
      path: '/track'
      fullPath: '/app/track'
      preLoaderRoute: typeof AppTrackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sellers': {
      id: '/app/sellers'
      path: '/sellers'
      fullPath: '/app/sellers'
      preLoaderRoute: typeof AppSellersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safepay': {
      id: '/app/safepay'
      path: '/safepay'
      fullPath: '/app/safepay'
      preLoaderRoute: typeof AppSafepayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pay': {
      id: '/app/pay'
      path: '/pay'
      fullPath: '/app/pay'
      preLoaderRoute: typeof AppPayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new-escrow': {
      id: '/app/new-escrow'
      path: '/new-escrow'
      fullPath: '/app/new-escrow'
      preLoaderRoute: typeof AppNewEscrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disputes': {
      id: '/app/disputes'
      path: '/disputes'
      fullPath: '/app/disputes'
      preLoaderRoute: typeof AppDisputesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/admin/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transaction/$id': {
      id: '/app/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/app/transaction/$id'
      preLoaderRoute: typeof AppTransactionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracking/$id': {
      id: '/app/tracking/$id'
      path: '/tracking/$id'
      fullPath: '/app/tracking/$id'
      preLoaderRoute: typeof AppTrackingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seller/$id': {
      id: '/app/seller/$id'
      path: '/seller/$id'
      fullPath: '/app/seller/$id'
      preLoaderRoute: typeof AppSellerIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppDisputesRoute: typeof AppDisputesRoute
  AppNewEscrowRoute: typeof AppNewEscrowRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPayRoute: typeof AppPayRoute
  AppSafepayRoute: typeof AppSafepayRoute
  AppScanRoute: typeof AppScanRoute
  AppSellersRoute: typeof AppSellersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrackRoute: typeof AppTrackRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppVerificationRoute: typeof AppVerificationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSellerIdRoute: typeof AppSellerIdRoute
  AppTrackingIdRoute: typeof AppTrackingIdRoute
  AppTransactionIdRoute: typeof AppTransactionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppDisputesRoute: AppDisputesRoute,
  AppNewEscrowRoute: AppNewEscrowRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPayRoute: AppPayRoute,
  AppSafepayRoute: AppSafepayRoute,
  AppScanRoute: AppScanRoute,
  AppSellersRoute: AppSellersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrackRoute: AppTrackRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppVerificationRoute: AppVerificationRoute,
  AppIndexRoute: AppIndexRoute,
  AppSellerIdRoute: AppSellerIdRoute,
  AppTrackingIdRoute: AppTrackingIdRoute,
  AppTransactionIdRoute: AppTransactionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SellerRouteChildren {
  SellerAccountRoute: typeof SellerAccountRoute
  SellerCustomersRoute: typeof SellerCustomersRoute
  SellerDeliveriesRoute: typeof SellerDeliveriesRoute
  SellerNotificationsRoute: typeof SellerNotificationsRoute
  SellerProtectedDealRoute: typeof SellerProtectedDealRoute
  SellerSafepayRoute: typeof SellerSafepayRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
  SellerTransactionsRoute: typeof SellerTransactionsRoute
  SellerVerificationRoute: typeof SellerVerificationRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAccountRoute: SellerAccountRoute,
  SellerCustomersRoute: SellerCustomersRoute,
  SellerDeliveriesRoute: SellerDeliveriesRoute,
  SellerNotificationsRoute: SellerNotificationsRoute,
  SellerProtectedDealRoute: SellerProtectedDealRoute,
  SellerSafepayRoute: SellerSafepayRoute,
  SellerSettingsRoute: SellerSettingsRoute,
  SellerTransactionsRoute: SellerTransactionsRoute,
  SellerVerificationRoute: SellerVerificationRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  SellerRoute: SellerRouteWithChildren,
  ShareRoute: ShareRoute,
  TermsRoute: TermsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthKycRoute: AuthKycRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRoleRoute: AuthRoleRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
